//Carousel
const carouselSlide = document.querySelector('.carousel-slide');
const carouselImages = document.querySelectorAll('.carousel-slide img');
const prevBtn = document.querySelector('#prevBtn');
const nextBtn = document.querySelector('#nextBtn');
let counter = 1;
const size = carouselImages[0].naturalWidth;


carouselSlide.style.transform = 'translateX(' + (-size * counter) + 'px)';

carouselSlide.addEventListener('transitionend',() => {
    if(carouselImages[counter].id === 'lastClone'){
        carouselSlide.style.transition = "none";
        counter = carouselImages.length - 2;
        carouselSlide.style.transform = 'translateX(' + (-size * counter) + 'px)';
    }
    if(carouselImages[counter].id === 'firstClone'){
        carouselSlide.style.transition = "none";
        counter = carouselImages.length - counter;
        carouselSlide.style.transform = 'translateX(' + (-size * counter) + 'px)';
    }
});

function carousel_next(){
    console.log("carousel_next works")
    if (counter >= carouselImages.length - 1) return;
    carouselSlide.style.transition = "transform 0.5s ease-in-out";
    counter++;
    carouselSlide.style.transform = 'translateX(' + (-size * counter) + 'px)';
}

function carousel_prev(){
    if (counter <= 0) return;
    carouselSlide.style.transition = "transform 0.5s ease-in-out";
    counter--;
    carouselSlide.style.transform = 'translateX(' + (-size * counter) + 'px)';
}

function getpickingarray(){
    //printf("get picked image button pressed!");
    const pickingarray = new Array(64).fill(0);
    if(counter == 1){
        pickingarray[0] = "orange";
        pickingarray[1] = "orange";
        pickingarray[2] = "orange";
        pickingarray[3] = "orange";
        pickingarray[4] = "orange";
        pickingarray[5] = "orange";
        pickingarray[6] = "orange";
        pickingarray[7] = "orange";
        pickingarray[8] = "orange";
        pickingarray[9] = "orange";
        pickingarray[10] = "orange";
        pickingarray[11] = "orange";
        pickingarray[12] = "orange";
        pickingarray[13] = "orange";
        pickingarray[14] = "orange";
        pickingarray[15] = "orange";
        pickingarray[16] = "orange";
        pickingarray[17] = "orange";
        pickingarray[18] = "purple";
        pickingarray[19] = "orange";
        pickingarray[20] = "orange";
        pickingarray[21] = "purple";
        pickingarray[22] = "orange";
        pickingarray[23] = "orange";
        pickingarray[24] = "orange";
        pickingarray[25] = "orange";
        pickingarray[26] = "orange";
        pickingarray[27] = "orange";
        pickingarray[28] = "purple";
        pickingarray[29] = "orange";
        pickingarray[30] = "orange";
        pickingarray[31] = "orange";
        pickingarray[32] = "orange";
        pickingarray[33] = "orange";
        pickingarray[34] = "orange";
        pickingarray[35] = "orange";
        pickingarray[36] = "orange";    
        pickingarray[37] = "orange";
        pickingarray[38] = "orange";
        pickingarray[39] = "orange";
        pickingarray[40] = "orange";
        pickingarray[41] = "purple";
        pickingarray[42] = "orange";
        pickingarray[43] = "orange";
        pickingarray[44] = "orange";
        pickingarray[45] = "orange";
        pickingarray[46] = "purple";
        pickingarray[47] = "orange";
        pickingarray[48] = "orange";
        pickingarray[49] = "purple";
        pickingarray[50] = "purple";
        pickingarray[51] = "purple";
        pickingarray[52] = "purple";
        pickingarray[53] = "purple";
        pickingarray[54] = "purple";
        pickingarray[55] = "orange";
        pickingarray[56] = "orange";
        pickingarray[57] = "orange";
        pickingarray[58] = "orange";
        pickingarray[59] = "orange";
        pickingarray[60] = "orange";
        pickingarray[61] = "orange";
        pickingarray[62] = "orange";
        pickingarray[63] = "orange";
    }
    else if(counter == 2){
        pickingarray[0] = "green";
        pickingarray[1] = "green";
        pickingarray[2] = "green";
        pickingarray[3] = "green";
        pickingarray[4] = "green";
        pickingarray[5] = "green";
        pickingarray[6] = "green";
        pickingarray[7] = "green";
        pickingarray[8] = "orange";
        pickingarray[9] = "orange";
        pickingarray[10] = "orange";
        pickingarray[11] = "orange";
        pickingarray[12] = "orange";
        pickingarray[13] = "orange";
        pickingarray[14] = "orange";
        pickingarray[15] = "orange";
        pickingarray[16] = "orange";
        pickingarray[17] = "orange";
        pickingarray[18] = "orange";
        pickingarray[19] = "orange";
        pickingarray[20] = "orange";
        pickingarray[21] = "orange";
        pickingarray[22] = "orange";
        pickingarray[23] = "orange";
        pickingarray[24] = "orange";
        pickingarray[25] = "orange";
        pickingarray[26] = "orange";
        pickingarray[27] = "orange";
        pickingarray[28] = "orange";
        pickingarray[29] = "orange";
        pickingarray[30] = "orange";
        pickingarray[31] = "orange";
        pickingarray[32] = "orange";
        pickingarray[33] = "orange";
        pickingarray[34] = "orange";
        pickingarray[35] = "orange";
        pickingarray[36] = "orange";    
        pickingarray[37] = "orange";
        pickingarray[38] = "orange";
        pickingarray[39] = "orange";
        pickingarray[40] = "orange";
        pickingarray[41] = "orange";
        pickingarray[42] = "orange";
        pickingarray[43] = "orange";
        pickingarray[44] = "orange";
        pickingarray[45] = "orange";
        pickingarray[46] = "orange";
        pickingarray[47] = "orange";
        pickingarray[48] = "orange";
        pickingarray[49] = "orange";
        pickingarray[50] = "orange";
        pickingarray[51] = "orange";
        pickingarray[52] = "orange";
        pickingarray[53] = "orange";
        pickingarray[54] = "orange";
        pickingarray[55] = "orange";
        pickingarray[56] = "purple";
        pickingarray[57] = "purple";
        pickingarray[58] = "purple";
        pickingarray[59] = "purple";
        pickingarray[60] = "purple";
        pickingarray[61] = "purple";
        pickingarray[62] = "purple";
        pickingarray[63] = "purple";
    }
    else if(counter == 3){
        pickingarray[0] = "green";
        pickingarray[1] = "green";
        pickingarray[2] = "green";
        pickingarray[3] = "green";
        pickingarray[4] = "green";
        pickingarray[5] = "green";
        pickingarray[6] = "green";
        pickingarray[7] = "green";
        pickingarray[8] = "orange";
        pickingarray[9] = "orange";
        pickingarray[10] = "orange";
        pickingarray[11] = "orange";
        pickingarray[12] = "orange";
        pickingarray[13] = "orange";
        pickingarray[14] = "orange";
        pickingarray[15] = "orange";
        pickingarray[16] = "orange";
        pickingarray[17] = "orange";
        pickingarray[18] = "orange";
        pickingarray[19] = "orange";
        pickingarray[20] = "orange";
        pickingarray[21] = "orange";
        pickingarray[22] = "orange";
        pickingarray[23] = "orange";
        pickingarray[24] = "orange";
        pickingarray[25] = "orange";
        pickingarray[26] = "orange";
        pickingarray[27] = "orange";
        pickingarray[28] = "orange";
        pickingarray[29] = "orange";
        pickingarray[30] = "orange";
        pickingarray[31] = "orange";
        pickingarray[32] = "orange";
        pickingarray[33] = "orange";
        pickingarray[34] = "orange";
        pickingarray[35] = "orange";
        pickingarray[36] = "orange";    
        pickingarray[37] = "orange";
        pickingarray[38] = "orange";
        pickingarray[39] = "orange";
        pickingarray[40] = "orange";
        pickingarray[41] = "orange";
        pickingarray[42] = "orange";
        pickingarray[43] = "orange";
        pickingarray[44] = "orange";
        pickingarray[45] = "orange";
        pickingarray[46] = "orange";
        pickingarray[47] = "orange";
        pickingarray[48] = "orange";
        pickingarray[49] = "orange";
        pickingarray[50] = "orange";
        pickingarray[51] = "orange";
        pickingarray[52] = "orange";
        pickingarray[53] = "orange";
        pickingarray[54] = "orange";
        pickingarray[55] = "orange";
        pickingarray[56] = "purple";
        pickingarray[57] = "purple";
        pickingarray[58] = "purple";
        pickingarray[59] = "purple";
        pickingarray[60] = "purple";
        pickingarray[61] = "purple";
        pickingarray[62] = "purple";
        pickingarray[63] = "purple";
    }
    else{
        pickingarray[0] = "green";
        pickingarray[1] = "green";
        pickingarray[2] = "green";
        pickingarray[3] = "green";
        pickingarray[4] = "green";
        pickingarray[5] = "green";
        pickingarray[6] = "green";
        pickingarray[7] = "green";
        pickingarray[8] = "orange";
        pickingarray[9] = "orange";
        pickingarray[10] = "orange";
        pickingarray[11] = "orange";
        pickingarray[12] = "orange";
        pickingarray[13] = "orange";
        pickingarray[14] = "orange";
        pickingarray[15] = "orange";
        pickingarray[16] = "orange";
        pickingarray[17] = "orange";
        pickingarray[18] = "orange";
        pickingarray[19] = "orange";
        pickingarray[20] = "orange";
        pickingarray[21] = "orange";
        pickingarray[22] = "orange";
        pickingarray[23] = "orange";
        pickingarray[24] = "orange";
        pickingarray[25] = "orange";
        pickingarray[26] = "orange";
        pickingarray[27] = "orange";
        pickingarray[28] = "orange";
        pickingarray[29] = "orange";
        pickingarray[30] = "orange";
        pickingarray[31] = "orange";
        pickingarray[32] = "orange";
        pickingarray[33] = "orange";
        pickingarray[34] = "orange";
        pickingarray[35] = "orange";
        pickingarray[36] = "orange";    
        pickingarray[37] = "orange";
        pickingarray[38] = "orange";
        pickingarray[39] = "orange";
        pickingarray[40] = "orange";
        pickingarray[41] = "orange";
        pickingarray[42] = "orange";
        pickingarray[43] = "orange";
        pickingarray[44] = "orange";
        pickingarray[45] = "orange";
        pickingarray[46] = "orange";
        pickingarray[47] = "orange";
        pickingarray[48] = "orange";
        pickingarray[49] = "orange";
        pickingarray[50] = "orange";
        pickingarray[51] = "orange";
        pickingarray[52] = "orange";
        pickingarray[53] = "orange";
        pickingarray[54] = "orange";
        pickingarray[55] = "orange";
        pickingarray[56] = "purple";
        pickingarray[57] = "purple";
        pickingarray[58] = "purple";
        pickingarray[59] = "purple";
        pickingarray[60] = "purple";
        pickingarray[61] = "purple";
        pickingarray[62] = "purple";
        pickingarray[63] = "purple";
    }
    document.getElementById("pickingforminput").value = pickingarray;
    document.getElementById("pickingform").submit();
    sessionStorage.setItem("pickingarray",JSON.stringify(pickingarray));
}